site_name: Ahmed Mousa Docs
site_description: توثيق مبدئي لمشروع حسوب
site_author: Ahmed Mousa

theme:
  name: material
  language: ar        # تعريب الواجهة
  direction: rtl      # محاذاة يمين وتخطيط RTL
  features:
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate

nav:
  - الرئيسية: index.md
  - الأسئلة الشائعة: faq.md
  - API: API_Documentation_Reqres_in_AhmedMousa.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - codehilite
  - footnotes
  - def_list
  - attr_list

# (اختياري) Google Analytics
 extra:
   analytics:
     provider: google
     property: G-5YZT4N3MPE

   
