# اسم الـ Workflow اللي هيظهر في GitHub Actions
name: Build & Deploy MkDocs

# التريجرز: إمتى يشتغل الـ Workflow؟
on:
  push:
    branches: [ main ]   # أي Push على فرع main
  workflow_dispatch:      # أو تشغيل يدوي من GitHub Actions

# إعطاء صلاحيات الكتابة عشان يقدر ينشر على فرع gh-pages
permissions:
  contents: write

jobs:
  # تعريف الـ Job الرئيسي
  build-deploy:
    runs-on: ubuntu-latest   # بيئة التشغيل: سيرفر Ubuntu مؤقت

    steps:
      # الخطوة 1: تنزيل نسخة من الريبو (الكود + الملفات)
      - name: Checkout
        uses: actions/checkout@v4

      # الخطوة 2: إعداد Python بإصدار 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # الخطوة 3: تثبيت MkDocs + ثيم Material
      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      # الخطوة 4: بناء الموقع (تحويل Markdown -> HTML)
      # --strict يخلي أي Warning يظهر كـ Error عشان تكتشف المشاكل بدري
      - name: Build site
        run: mkdocs build --strict

      # الخطوة 5: نشر الموقع على GitHub Pages
      # بيستخدم أكشن جاهز (peaceiris/actions-gh-pages)
      # بياخد الملفات من مجلد site/ ويرفعها على فرع gh-pages
      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # توكن مدمج من GitHub
          publish_dir: ./site                         # ملفات HTML الناتجة
          publish_branch: gh-pages                    # الفرع اللي هيتنشر عليه
